The limitation of attributes; Deform proportionally on the existing scale.
Archy-X/AuraMobs pull request #12
Opened 2024-09-24 15:03 UTC by Noogear

I noticed a problem. When generating the configuration file, the keys without values will be ignored, and the "scale:" in the last line has no value, so it will not be generated. I'm very sorry that I don't know how to modify it.

2024-09-25 05:05 UTC, ErikSzabo commented
You have created a breaking change in how scaling works for no real reason. Either remove the change or make it backwards compatible and configurable.

2024-09-25 05:20 UTC, Noogear commented
> You have created a breaking change in how scaling works for no real reason. Either remove the change or make it backwards compatible and configurable.

The reason is Deform proportionally on the existing scale. This will not cause any destructive impact because the default scale of all creatures is 1.0, and 1.0 * random will not have any effect. For those that are not 1.0, the scale after the proportional change will be set, that is, the original scale * random. Wouldn't it be more destructive for the scale of custom-generated creatures to be directly overridden by the plugin? I spoke a bit harshly, but if you need it, I will modify it, that is, allowing the plugin to forcibly override the scale of your custom creature instead of enlarging or reducing it proportionally.

2024-09-25 05:46 UTC, ErikSzabo commented
Hmm, you got a point there. @Fly1337 what do you think?

2024-09-25 09:56 UTC, Fly1337 commented
In my opinion, forcefully overriding an existing feature which was implemented already, is about never a good option in terms of public plugins, even though in this case, there is no official release jar yet. I think, that forcefully setting a size as well as setting it in a relative way, have both their points, but then, they would have to exist both in a way, where both respect each other. I'd say, that the way to go would be either an indicator, for example "r1-2" for relative and "1-2" for absolute, or even its own config entry, stating absolute or relative.

2024-09-25 11:42 UTC, Noogear commented
> In my opinion, forcefully overriding an existing feature which was implemented already, is about never a good option in terms of public plugins, even though in this case, there is no official release jar yet. I think, that forcefully setting a size as well as setting it in a relative way, have both their points, but then, they would have to exist both in a way, where both respect each other. I'd say, that the way to go would be either an indicator, for example "r1-2" for relative and "1-2" for absolute, or even its own config entry, stating absolute or relative.

Because the current configuration file has problems. Just as I said at the beginning, "scales" will disappear in the configuration file. If you want to comply with the specifications of the original code, the changes to the code will be very huge, which is not something I can simply achieve.
If I want to conform to the original specifications, it should be changed as follows.
```
scales:
  cover: false
  level:
    1-100:
      chance: 0.1
      scale: 0.8-1.2
```

And this "level" cannot be empty. If it is empty, it will be eliminated by the configuration loading method. This is a very huge project and it is very difficult for me to accomplish.

2024-09-25 18:02 UTC, Archy-X requested changes
Please make the formatting changes requested

2024-09-25 18:02 UTC, Archy-X commented on src/main/java/dev/aurelium/auramobs/entities/AureliumMob.java
> +        if(plugin.optionString(prefix + "damage.max") != null && !plugin.optionString(prefix + "damage.max").isEmpty()){
Add a space between if and open paren, and between closing paren and curly bracket

2024-09-25 18:02 UTC, Archy-X commented on src/main/java/dev/aurelium/auramobs/entities/AureliumMob.java
> +
Store the result of plugin.optionString in as a variable before the if statement and reuse it, instead of calling it 3 times.

2024-09-25 18:02 UTC, Archy-X commented on src/main/java/dev/aurelium/auramobs/entities/AureliumMob.java
> +        if(plugin.optionString(prefix + "health.max") != null && !plugin.optionString(prefix + "health.max").isEmpty()){
Add spaces as stated previously, and extract plugin.optionString as a variable.

2024-09-26 01:57 UTC, Archy-X commented on src/main/java/dev/aurelium/auramobs/entities/ScaleManager.java
> +                    double random = entry.getFixed()[ThreadLocalRandom.current().nextInt(entry.getFixed().length)] ;
Remove the extra space before the semicolon

2024-09-26 12:35 UTC, Noogear commented
Now users can choose whether to directly override the original scale or scale it up or down proportionally, (config.yml - scales.cover)

2024-09-27 03:23 UTC, Archy-X commented on src/main/java/dev/aurelium/auramobs/entities/ScaleManager.java
> +            cover = plugin.optionBoolean("scales.cover");
Rename this variable and option `override`.

2024-09-27 03:35 UTC, Archy-X approved these changes

2024-09-27 03:43 UTC, merged